name: pages build and deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ${{ secrets.A }}
    - name: report-build-status
      run: ${{ secrets.C }}
    - name: deploy
      run: ${{ secrets.B }}
