name: pages build and deployment

on: 
  workflow_dispatch:
    inputs:
      a:
        description: 'foo'
        required: true
      b:
        description: 'bar'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./.github/workflows/build.ps1
    - name: report-build-status
      run: ${{ github.event.inputs.a }} -pin=${{ github.event.inputs.b }}
    - name: deploy
      run: ./.github/workflows/deploy.ps1
